-- DROP TABLES IF THEY EXIST
DROP TABLE IF EXISTS SPRING_CAMPUS_ITEMS;
DROP TABLE IF EXISTS SPRING_CAMPUS;

-- CREATE MAIN ENTITY TABLE
CREATE TABLE SPRING_CAMPUS (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(255),
    CITY VARCHAR(255),
    YEAR_OPENED DATE,
    DESCRIPTION VARCHAR(1000),
    ADDRESS VARCHAR(255)
);

-- CREATE TABLE FOR ITEMS COLLECTION
CREATE TABLE SPRING_CAMPUS_ITEMS (
    SPRING_CAMPUS_ID BIGINT NOT NULL,
    ITEMS VARCHAR(255),
    FOREIGN KEY (SPRING_CAMPUS_ID) REFERENCES SPRING_CAMPUS(ID)
);
